export enum API_TAGS {
  USER = "User",
  SETTINGS = "Settings",
  ANALYSIS = "Analysis",
  PATIENTS = "Patient",
  EXAMS = "Exams",
  PRESCRIPTION = "Prescription",
  IMAGES = "Images",
  BILLING = "Billing",
  CORPUS = "CORPUS",
  ROOM = "ROOM",
  IMAGING_TYPE = "ImagingType",
  MEDICAL_IMAGE = "MedicalImage",
  DISEASE = "DISEASE",
}
